### ISSUE TITLE
docker-compose build fails

### ISSUE THREAD

**Issue by andrehe001** [microsoft/SmartHotel360#1]
when running docker-compose build for the images I get the error: "./mvnw nor found..." see picture. I tried it in powershell and bash with the same result. I'm in the right dir /src. 

It looks like I have to work with Linux container in Docker and not with Windows containers, correct?

![docker-compose_failure](https://user-images.githubusercontent.com/13762183/34069689-24c734cc-e256-11e7-83c0-4e59858915fd.png)

**Comment by MFTTech** [comment]
Same here. I posted issue to backend repo.
Are you also getting the steam parameter can't be null when you try to build all from visual studio?

**Comment by andrehe001** [comment]
I haven't try to build the solution in VS so far as I struggled already with the containers. Will try it and post the results.

**Comment by andrehe001** [comment]
I've build the smarthotel360 website project and it went through without problems. What I had to do is rebuild the node-sass libraries with **npm rebuild node-sass --force** right in the node_modules folder. Still the docker-compose doesn't work.

**Comment by MFTTech** [comment]
Stream parameter error I mentioned is when building backend services solution.

**Comment by andrehe001** [comment]
Got it. Tried the backend part with build all and received the error you mentioned above. "Parameter name: stream; value cannot be null.

**Comment by eiximenis** [comment]
Hi. The "Parameter name stream" error is due to a bug of VS :(

For the mvnw not found, i suspect i could be due to a line ending issue (probably local file has CRLF line ending and should have only LF). I will push a .gitattributres file to fix that a bit later.

**Comment by andrehe001** [comment]
thanks for the update. Looking forward to install it once it's fixed.

**Comment by MFTTech** [comment]
I'm 0/3 (Backend/Web/Mobile)

**Comment by npagare** [comment]
same issue also posted at - https://forums.xamarin.com/discussion/113209/introducing-the-smarthotel360-reference-mobile-apps/p1?new=1

This is a great reference app to learn lots of new relevant and cutting edge technologies and concepts.
Waiting for the error-free and compilable code ready across all solutions / projects / tech stacks.

**Comment by eiximenis** [comment]
Hi!
"Stream parameter error" is solved in VS 15.6 (currently in Preview 2).

Line ending errors should be solved too. Could you confirm with a fresh clone?

**Comment by bradygmsft** [comment]
@IoTFier - Have you tried following @eiximenis' commentary? Is this still broken?

**Comment by bradygmsft** [comment]
@IoTFier - I think we've identified this as a closed issue once the upgrade to 15.5/6 is completed. Please re-open if this isn't a resolved issue and we'll work towards a resolution.

**Comment by npagare** [comment]
Hi @bradygmsft , the docker-compose is still failing in VS 15.5.6 (just upgraded an hour ago or so)
See the screenshots below. Regarding mvnw issue, I didn't see that update in the GitHub.

![image](https://user-images.githubusercontent.com/26844611/35583760-8dc6f964-05b8-11e8-8573-42d54e6c3061.png)

![image](https://user-images.githubusercontent.com/26844611/35583737-7c2a9c38-05b8-11e8-8dbc-13653bff34be.png)

**Comment by npagare** [comment]
@bradygmsft please keep this issue open until we get docker-compose working fully within Visual Studio 15.5.x Thanks

**Comment by eiximenis** [comment]
Hi.
From your last capture I can't see what is the error you're facing with the docker-compose.

Also a `docker-compose build` from CLI works?

**Comment by stewartnoll** [comment]
@bradygmsft pulled down the latest VS 2017 Preview (15.6.0 Preview 5.0) per @eiximenis recommendation but still getting the error `Value cannot be null.  Parameter name: stream`.  Can't say for certain that there was a regression between Preview 2.0 and Preview 5.0 that reintroduced the error without further investigating.

`docker-compose build` from the CLI works perfectly fine.

**Comment by eiximenis** [comment]
Hi. I tested again in VS15.6.0 Preview 5 and the error is back again :(

**There is nothing we can do on our side** as this is a VS bug. There are two workarounds:

1. Remove node project from docker-compose.yml file, removing following lines:
``` 
  suggestions-api:
    image: smarthotels/suggestions
    build:
      context: ./SmartHotel.Services.Suggestions
      dockerfile: Dockerfile
```

Also remove following lines from docker-compose.override.yml:

```
  suggestions-api:
    environment:
      - PORT=80
      - SUGGESTIONS_DATABASE_URL=mssql://sa:Passw0rd!@sql-data:1433/SuggestionsDb
      - NODE_ENV=docker
    ports:
      - "6102:80"
```

That won't start suggestions API neither from VS nor from CLI.

2. Remove entire dcproj from solution. In this case you can't run on Docker by using VS :(


**PS: I reopened the issue just to track any progresss on this.**

**Comment by bradygmsft** [comment]
I checked in with engineering folks on the tooling team and they're investigating this.

**Comment by diegofal** [comment]
Hello guys, I am getting this error on version 15.6.6.
  Has anyone solved it? 

Thanks!
